# Generated by Django 4.2.2 on 2023-06-23 01:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0004_delete_locations"),
    ]

    operations = [
        migrations.CreateModel(
            name="Locations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
    ]
